name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.8
homepage: https://github.com/appsup-dart/openid_client
funding:
  - https://github.com/sponsors/rbellens

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  jose: ^0.3.4
  pointycastle: ^3.7.4
  http: ^1.2.1
  logging: ^1.2.0
  args: ^2.4.2
  meta: ^1.11.0
  clock: ^1.1.1

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0

executables:
  openid_client: openid_client
